---
# tasks file for myapache
- package:
        name: "httpd"
        state: "present"
   
- copy:
        src: "hello.html"
        dest: "/var/www/html/"

- service:
        name: "httpd"
        state: started
 
